### PR TITLE
Fix that script is not working on Windows

### PR DESCRIPTION
**Pull request by Sn1cket**
When executing `python -m makefile_creator` on Windows command line the script finishes without console output and doesn't create the makefiles.

### CODE REVIEW

**Comment by m3sserschmitt** [comment]
This script was not intended for Windows OS, and was tested on Linux only. Your effort is really appreciated! Thanks!

**Comment by m3sserschmitt** [comment]
Any further improvements are welcome.

**Review by m3sserschmitt — COMMENTED** [review]
Looks great

**Comment by Sn1cket** [comment]
@m3sserschmitt  Would you mind creating a new PyPi release with this changes?

**Pull request merged**
